### ISSUE TITLE
'Error: Version string must look like semver (eg '1.2.3')' - Cannot package app

### ISSUE THREAD

**Issue by chrisjgjm** [sujith3g/meteor-cordova-google-plus#18]
```
hedcet:cordova-google-plus-native-sign-in  added, version 1.1.3

/Users/mycomputer/.meteor/packages/meteor-tool/.1.4.4_1.1ygrsyx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
Error: Version string must look like semver (eg '1.2.3'), not 'https://github.com/meteor/cordova-plugin-googleplus.git#3095abe327e710ab04059ae9d3521bd4037c5a37'.
```
Has anyone experienced this and found a solution?

**Comment by davinderkumar** [comment]
I'm getting same problem when trying to compile the project.

**Comment by HedCET** [comment]
@sujith3g i think issue in here https://github.com/sujith3g/meteor-cordova-google-plus/blob/master/package.js#L10

**Comment by sujith3g** [comment]
It is already in semver (`5.1.1`) [here](https://github.com/sujith3g/meteor-cordova-google-plus/commit/62ee97ef675ef0e2fd68740e83424fe96b406fd0#diff-49fb32b6d8276ecd1268e47c0339d55c)

**Comment by sujith3g** [comment]
Please upgrade `hedcet:cordova-google-plus-native-sign-in` to `1.1.3` and try. and provide details about which version of `Meteor` , `hedcet:cordova-google-plus-native-sign-in`, `android` is used

**Comment by evanoralph** [comment]
still getting the error, already updated to 1.1.3

**Comment by davinderkumar** [comment]
same problem with 1.1.3.
I'm on Meteor 1.4.4.2 on Mac.

Complete error:
Error: Version string must look like semver (eg '1.2.3'), not 'https://github.com/meteor/cordova-plugin-googleplus.git#3095abe327e710ab04059ae9d3521bd4037c5a37'.

**Comment by evanoralph** [comment]
@davinderkumar hi 

I got mine working by forking it and install the fork version on my project try to search how to install custom meteor packages without atmosphere 

i hope this help cheers !!

**Comment by harpreetsimpinge** [comment]
@evanoralph I implemented it in my codebase directly :)

**Comment by HedCET** [comment]
just change ```Cordova``` to ```Npm``` it will work https://github.com/sujith3g/meteor-cordova-google-plus/blob/master/package.js#L9
