### ISSUE TITLE
switch to npm

### ISSUE THREAD

**Issue by HedCET** [sujith3g/meteor-cordova-google-plus#7]

**Comment by teknologist** [comment]
Would this allow you to upgrade to the more recent versions of the upstream cordova plugin ? i.e. 4.0.x ?

That'd be great, as the current upstream (1.1.2) doesn't seem to work in a reliable manner on iOS...

**Comment by HedCET** [comment]
@teknologist i don't know its backward compatible, anyway updated 0.0.15 (MeteorJS-1.1) to 0.1.0 (MeteorJS-1.2)
