### ISSUE TITLE
Problem on iOS

### ISSUE THREAD

**Issue by teknologist** [sujith3g/meteor-cordova-google-plus#8]
Hi,
I can't make it work on iOS.

After launching Google+ and the consent page, when I click OK, It just doesn return to my meteor app and it stays logged out.

It maybe related to REVERSED_CLIENT_ID which I don't know where to put for the iOS cordova build.

Or the file GoogleService-Info.plist... Do I need to  add it somewhere in Xcode ?

Many thanks in advance!

Eric

**Comment by teknologist** [comment]
Solved. Adding the plist file to Xcode and adding REVERSE_CLIENT_ID to apps plist

**Comment by oskarszoon** [comment]
@teknologist How did you get the plugin added? Meteor is throwing an error when i just add the package:

```
Failed to install 'cordova-plugin-googleplus':Error: Variable(s) missing: REVERSED_CLIENT_ID
```

**Comment by oskarszoon** [comment]
Nevermind, found it. For future reference you need to add the following to your mobile-config.json

```
App.configurePlugin('cordova-plugin-googleplus', {
    'REVERSED_CLIENT_ID': 'com.googleusercontent.apps.XXXXXX'
});
```

Here's the link on how to generate the REVERSED_CLIENT_ID for iOS: https://github.com/EddyVerbruggen/cordova-plugin-googleplus#3-google-api-setup

**Comment by jetlej** [comment]
BTW in 2017 it's `mobile-config.js` (not .json)
